version: "3.8"
services:
  haptic-imitation:
    image: haptic-imitation:${USER}
    container_name: haptic-imitation
    working_dir: /home/user/haptic-imitation
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      # - /home/${USER}/.config/barrett:/etc/barrett
      - ../haptic-imitation:/home/user/haptic-imitation
      - /tmp/.X11-unix:/tmp/.X11-unix
